Description of demo1
Home > sgwt_toolbox > demo > demo1.m
demo1
PURPOSE
demo1 : SGWT for swiss roll data set
SYNOPSIS
function demo1
DESCRIPTION
 demo1 : SGWT for swiss roll data set
 This demo builds the SGWT for the swiss roll synthetic data set. It
 computes a set of scales adapted to the computed upper bound on the
 spectrum of the graph Laplacian, and displays the scaling function and
 the scaled wavlet kernels, as well as the corresponding frame bounds. It
 then computes the wavelets centered on a single vertex, and displays
 them. This essentally reproduces figure 3 from
 Hammond,Vangergheynst, Gribonval 2010.
CROSS-REFERENCE INFORMATION
This function calls:
create_synthetic_dataset create_synthetic_dataset creates test data for running nldr algorithms.
distanz DISTANZ calcs the distances between all vectors in x and y.
rescale_center rescale_center
sgwt_cheby_coeff sgwt_cheby_coeff : Compute Chebyshev coefficients of given function
sgwt_cheby_op sgwt_cheby_op : Chebyshev polynomial of Laplacian applied to vector
sgwt_delta sgwt_delta : Return vector with one nonzero entry equal to 1.
sgwt_filter_design sgwt_filter_design : Return list of scaled wavelet kernels and derivatives
sgwt_laplacian sgwt_laplacian : Compute graph laplacian from connectivity matrix
sgwt_rough_lmax sgwt_rough_lmax : Rough upper bound on maximum eigenvalue of L
sgwt_view_design
This function is called by:
SUBFUNCTIONS
function clean_axes(cp)
SOURCE CODE
% demo1 : SGWT for swiss roll data set
%
% This demo builds the SGWT for the swiss roll synthetic data set. It
% computes a set of scales adapted to the computed upper bound on the
% spectrum of the graph Laplacian, and displays the scaling function and
% the scaled wavlet kernels, as well as the corresponding frame bounds. It
% then computes the wavelets centered on a single vertex, and displays
% them. This essentally reproduces figure 3 from
% Hammond,Vangergheynst, Gribonval 2010.
% Create swiss roll point cloud
function demo1
close all
fprintf('Welcome to SGWT demo #1\n');
npoints=500;
fprintf('Creating Swiss Roll point cloud with %g points\n',npoints);
dataparams=struct('n',npoints,'dataset',-1','noise',0,'state',0);
r=create_synthetic_dataset(dataparams);
x=rescale_center(r.x);
fprintf('Computing edge weights and graph Laplacian\n');
% Compute Weighted graph adjacency matrix, and graph Laplacian
d=distanz(x);
s=.1;
A=exp(-d.^2/(2*s^2));
L=full(sgwt_laplacian(A));
fprintf('Measuring largest eigenvalue, lmax = ');
%% Design filters for transform
Nscales=4;
lmax=sgwt_rough_lmax(L);
fprintf('%g\n',lmax);
fprintf('Designing transform in spectral domain\n');
[g,gp,t]=sgwt_filter_design(lmax,Nscales);
arange=[0 lmax];
%% Display filter design in spectral domain
figure
sgwt_view_design(g,t,arange);
ylim([0 3])
set(gcf,'position',[0 780,600,300])
%% Chebyshev polynomial approximation
m=50; % order of polynomial approximation
fprintf('Computing Chebyshev polynomials of order %g for fast transform \n',m);
for k=1:numel(g)
  c{k}=sgwt_cheby_coeff(g{k},m,m+1,arange);
end
%% compute transform of delta at one vertex
jcenter=32; % vertex to center wavelets to be shown
fprintf('Computing forward transform of delta at vertex %g\n',jcenter);
N=size(L,1);
d=sgwt_delta(N,jcenter);
% forward transform, using chebyshev approximation
wpall=sgwt_cheby_op(d,L,c,arange);
fprintf('Displaying wavelets\n');
msize=100;
cp=[-1.4,-16.9,3.4]; % camera position
%% Visualize result
% show original point
ws=300;
figure;
xp=0; yp=ws+100;
set(gcf,'position',[xp,yp,ws-10,ws+10]);
scatter3(x(1,:),x(2,:),x(3,:),msize,d,'.');
set(gcf,'Colormap',[.5 .5 .5;1 0 0]);
clean_axes(cp);
title(sprintf('Vertex %g',jcenter));
% show wavelets
for n=1:Nscales+1
    wp=wpall{n};
    figure
    xp=mod(n,3)*(ws+10);
    yp=(1-floor((n)/3))*(ws+100);
    set(gcf,'position',[xp,yp,ws-10,ws+10]);
    scatter3(x(1,:),x(2,:),x(3,:),msize,wp,'.');
    colormap jet
    caxis([-1 1]*max(abs(wp)));
    clean_axes(cp);
    hcb=colorbar('location','north');
    cxt=get(hcb,'Xtick');
    cxt=[cxt(1),0,cxt(end)];
    set(hcb,'Xtick',cxt);
    cpos=get(hcb,'Position');
    cpos(4)=.02; % make colorbar thinner
    set(hcb,'Position',cpos);
    set(hcb,'Position',[.25 .91 .6 .02]);
    if n==1
      title('Scaling function');
    else
      title(sprintf('Wavelet at scale j=%g, t_j = %0.2f',n-1,t(end+1-(n-1))));
    end
end
function clean_axes(cp)
xlim([-1 1]);ylim([-1 1]);zlim([-1 1]);
set(gca,'Xtick',[-1 0 1]);
set(gca,'Ytick',[-1 0 1]);
set(gca,'Ztick',[-1 0 1]);
axis square
set(gca,'CameraPosition',cp);